import "./globals.css";

import { Athiti } from "next/font/google";
const athiti = Athiti({
  weight: ["200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "ConfPlus",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={athiti.className}>{children}</body>
    </html>
  );
}
